"""alter custom_alias

Revision ID: a04ea2ad0b36
Revises: b524ee69a8c1
Create Date: 2023-10-29 23:41:31.235661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04ea2ad0b36'
down_revision = 'b524ee69a8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_alias', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('custom_alias')

    # ### end Alembic commands ###
